CREATE TABLE APP.CAR_BRAND (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
brand VARCHAR(100) NOT NULL  unique,
primary key(id)
);

CREATE TABLE APP.CAR_MODEL (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
model VARCHAR(100) NOT NULL,
fk_car_brand INTEGER NOT NULL REFERENCES APP.CAR_BRAND,
primary key(id)
);

CREATE TABLE APP.CAR (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
car_year INTEGER NOT NULL,
fk_car_model INTEGER NOT NULL REFERENCES APP.CAR_MODEL,
form_factor INTEGER NOT NULL,
primary key(id)
);

CREATE TABLE APP.PART (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
part_name VARCHAR(100) NOT NULL,
category INTEGER NOT NULL,
is_user BOOLEAN NOT NULL,
primary key(id)
);

CREATE TABLE APP.PART_REQUEST (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
fk_car INTEGER NOT NULL REFERENCES APP.CAR,
fk_part INTEGER NOT NULL REFERENCES APP.PART,
serial_num VARCHAR(100),
shop_price INTEGER, 
primary key(id)
);

CREATE TABLE APP.AUTHORISE_INFO (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
pass VARCHAR(40) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
primary key(id)
);

CREATE TABLE APP.CITY(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
city VARCHAR(100) NOT NULL UNIQUE,
primary key(id)
);

CREATE TABLE APP.SELLER(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
primary key(id),
sell_name VARCHAR(100) NOT NULL,
city INTEGER REFERENCES APP.CITY NOT NULL,
phone VARCHAR(15) NOT NULL,
email VARCHAR(50) NOT NULL,
fk_auth_info INTEGER REFERENCES APP.AUTHORISE_INFO NOT NULL
);

CREATE TABLE APP.CUSTOMER(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
primary key(id),
nickname VARCHAR(80) NOT NULL,
fk_city INTEGER REFERENCES APP.CITY NOT NULL,
fk_auth_inf INTEGER REFERENCES APP.AUTHORISE_INFO NOT NULL
);

CREATE TABLE APP.PART_FOR_SALE (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
fk_car_model INTEGER NOT NULL REFERENCES APP.CAR_MODEL,
category INTEGER,
form_factor INTEGER,
fk_part INTEGER REFERENCES APP.PART,
fk_seller INTEGER REFERENCES APP.SELLER NOT NULL,
yearSince INTEGER NOT NULL,
yearUntil INTEGER NOT NULL,
primary key(id)
);

CREATE TABLE APP.CUSTOMERS_CARS(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
fk_cust INTEGER REFERENCES APP.CUSTOMER NOT NULL,
fk_car INTEGER REFERENCES APP.CAR NOT NULL
);

CREATE TABLE APP.TENDER(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
primary key(id),
fk_part_request INTEGER REFERENCES APP.PART_REQUEST NOT NULL,
fk_customer INTEGER REFERENCES APP.CUSTOMER NOT NULL,
create_date TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE APP.NOTIFICATION(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
primary key(id),
create_date TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP,
fk_sell INTEGER REFERENCES APP.SELLER NOT NULL,
fk_tender INTEGER REFERENCES APP.TENDER ON DELETE CASCADE NOT NULL
);

CREATE TABLE APP.BID(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
primary key(id),
cost INTEGER,
add_inf VARCHAR(500), 
create_date TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP,
fk_tender INTEGER REFERENCES APP.TENDER ON DELETE CASCADE NOT NULL,
fk_seller INTEGER REFERENCES APP.SELLER NOT NULL
);

ALTER TABLE APP.CUSTOMER DROP fk_CUST_INF
ALTER TABLE APP.CUSTOMER ADD  nickname VARCHAR(40) NOT NULL UNIQUE WITH DEFAULT ''
ALTER TABLE APP.CUSTOMER ADD fk_city INTEGER REFERENCES APP.CITY NOT NULL WITH DEFAULT 0
DROP TABLE APP.CAR
ALTER TABLE APP.CAR ADD fk_brand INTEGER REFERENCES APP.CAR_BRAND NOT NULL WITH DEFAULT 0
ALTER TABLE APP.CAR ADD fk_model INTEGER REFERENCES APP.CAR_MODEL NOT NULL WITH DEFAULT 0
ALTER TABLE APP.PART DROP category
ALTER TABLE APP.PART ADD category INTEGER NOT NULL WITH DEFAULT 0
ALTER TABLE APP.PART ADD part_name VARCHAR(80) NOT NULL WITH DEFAULT 'unknown part'
ALTER TABLE APP.BID DROP photo
ALTER TABLE APP.PART_REQUEST ADD shop_cost INTEGER

ALTER TABLE APP.TENDER DROP create_date
ALTER TABLE APP.TENDER ADD create_date  TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP
INSERT INTO APP.TENDER (create_date) VALUES (CURRENT_TIMESTAMP);
 
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
car_year INTEGER NOT NULL,
fk_car_model INTEGER NOT NULL REFERENCES APP.CAR_MODEL,
fk_form_factor INTEGER NOT NULL REFERENCES APP.FORM_FACTOR,
primary key(id)
)

INSERT INTO APP.CAR_BRAND(brand) VALUES('Ford');
INSERT INTO APP.CAR_BRAND(brand) VALUES('Toyota');
INSERT INTO APP.CAR_BRAND(brand) VALUES('Honda');

INSERT INTO APP.CAR_MODEL(model,fk_car_brand) VALUES('Focus',1);
INSERT INTO APP.CAR_MODEL(model,fk_car_brand) VALUES('Mondeo',1);
INSERT INTO APP.CAR_MODEL(model,fk_car_brand) VALUES('Tempo',1);
INSERT INTO APP.CAR_MODEL(model,fk_car_brand) VALUES('Corolla',2);
INSERT INTO APP.CAR_MODEL(model,fk_car_brand) VALUES('Crown',2);
INSERT INTO APP.CAR_MODEL(model,fk_car_brand) VALUES('RAV 4',2);
INSERT INTO APP.CAR_MODEL(model,fk_car_brand) VALUES('Civic',3);
INSERT INTO APP.CAR_MODEL(model,fk_car_brand) VALUES('Accord',3);
INSERT INTO APP.CAR_MODEL(model,fk_car_brand) VALUES('Jazz',3);

INSERT INTO APP.CITY(city) VALUES('Санкт-Петербург');
INSERT INTO APP.CITY(city) VALUES('Москва');

INSERT INTO APP.PART(part_name, category, is_user) VALUES('крыло переднее левое',4,FALSE);
INSERT INTO APP.PART(part_name, category, is_user) VALUES('крыло переднее правое',4,FALSE);
INSERT INTO APP.PART(part_name, category, is_user) VALUES('капот',4,FALSE);
INSERT INTO APP.PART(part_name, category, is_user) VALUES('решетка радиатора',4,FALSE);
INSERT INTO APP.PART(part_name, category, is_user) VALUES('решетка радиатора',4,FALSE);
INSERT INTO APP.PART(part_name, category, is_user) VALUES('обшивка потолка',1,FALSE);
INSERT INTO APP.PART(part_name, category, is_user) VALUES('задний диван',1,FALSE);
INSERT INTO APP.PART(part_name, category, is_user) VALUES('рулевое колесо',1,FALSE);
INSERT INTO APP.PART(part_name, category, is_user) VALUES('форсунка',9,FALSE);
INSERT INTO APP.PART(part_name, category, is_user) VALUES('свеча зажигания',9,FALSE);

DROP TABLE APP.AUTHORISE_INFO;
DROP TABLE APP.BID;
DROP TABLE APP.CAR;
DROP TABLE APP.CUSTOMER;
DROP TABLE APP.CUSTOMERS_CARS;
DROP TABLE APP.NOTIFICATION;
DROP TABLE APP.PART_FOR_SALE;
DROP TABLE APP.PART_REQUEST;
DROP TABLE APP.CAR_BRAND;
DROP TABLE APP.CAR_MODEL;
DROP TABLE APP.CITY;
DROP TABLE APP.PART;
DROP TABLE APP.SELLER;
DROP TABLE APP.TENDER;




SELECT APP.CAR_BRAND.id, APP.CAR_BRAND.brand, APP.CAR_MODEL.model
FROM APP.CAR_BRAND
INNER JOIN 
APP.CAR_MODEL
ON APP.CAR_MODEL.fk_car_brand=APP.CAR_BRAND.id
WHERE APP.CAR_MODEL.model='Tempo'


CREATE TABLE APP.TEST(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
primary key(id),
create_date TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP
)
ALTER TABLE APP.TEST ADD str VARCHAR(50);
ALTER TABLE APP.TEST ADD val INTEGER WITH DEFAULT NULL;

ALTER TABLE APP.SELLER ADD phone VARCHAR(20) NOT NULL WITH DEFAULT '';
ALTER TABLE APP.SELLER ADD email VARCHAR(30) NOT NULL WITH DEFAULT '';
ALTER TABLE APP.SELLER ADD company_name VARCHAR(60) NOT NULL WITH DEFAULT '';
ALTER TABLE APP.SELLER DROP fk_sell_info;
ALTER TABLE APP.SELLER ADD fk_city INTEGER NOT NULL REFERENCES APP.CITY WITH DEFAULT 0;

ALTER TABLE APP.CAR DROP fk_form_factor;
ALTER TABLE APP.CAR ADD form_factor INT NOT NULL WITH DEFAULT 0;
ALTER TABLE APP.TENDER ADD add_info VARCHAR(500) WITH DEFAULT '';

ALTER TABLE APP.PART_FOR_SALE DROP fk_form_factor;
ALTER TABLE APP.PART_FOR_SALE ADD form_factor INT NOT NULL WITH DEFAULT 0;

ALTER TABLE APP.PART_FOR_SALE DROP fk_category;
ALTER TABLE APP.PART_FOR_SALE ADD category INT NOT NULL WITH DEFAULT 0;

SELECT brand FROM APP.CAR_MODEL
    INNER JOIN APP.CAR_BRAND 
    ON APP.CAR_MODEL.FK_CAR_BRAND=APP.CAR_BRAND.ID
WHERE APP.CAR_MODEL.ID=5;


SELECT APP.PART_FOR_SALE.category, APP.PART_FOR_SALE.fk_part, APP.PART_FOR_SALE.form_factor 
		 FROM APP.PART_FOR_SALE 
		 WHERE APP.PART_FOR_SALE.fk_car_model=1 AND 
		 APP.PART_FOR_SALE.yearsince <= 1997 AND 
		 APP.PART_FOR_SALE.yearuntil >= 1997;

JOIN APP.PART ON APP.PART.id = APP.PART_FOR_SALE.fk_part 
		 JOIN APP.SELLER ON APP.SELLER.id=APP.PART_FOR_SALE.fk_seller
DROP TABLE APP.CAR;

SELECT brand FROM APP.CAR_BRAND 
				 INNER JOIN APP.CAR_MODEL 
				 ON APP.CAR_MODEL.FK_CAR_BRAND=APP.CAR_BRAND.ID 
				 WHERE APP.CAR_MODEL.ID=5

SELECT * FROM APP.TENDER WHERE id=100;