/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.Car.DBCarBrand;
import BusinessLogic.Car.DBCarModel;
import BusinessLogic.Part.Converter;
import BusinessLogic.Part.Part;
import BusinessLogic.Part.PartForSale;
import BusinessLogic.Seller;
import Exceptions.DBInteractionException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HOME
 */
public class NewPartForSale extends javax.swing.JDialog {

    /**
     * Creates new form NewPartForSale
     */
    public NewPartForSale(java.awt.Frame parent, boolean modal, Seller sell) {
	super(parent, modal);
	initComponents();
	this.seller=sell;
	try {
	    for(String cb : DBCarBrand.getBrandList()){
		this.jComboBoxBrand.addItem(cb);
	    }
	} catch (DBInteractionException ex) {
    	    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
	    Logger.getLogger(CarAdding.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
	}
	
	this.jComboBoxFF.addItem(new String(""));
	for(String ff : Converter.getFactorList()){
	    this.jComboBoxFF.addItem(ff);
	}
	
	this.jComboBoxCat.addItem(new String(""));
	for(String c : Converter.getCategoryList()){
	    this.jComboBoxCat.addItem(c);
	}
	
    }
    
    Seller seller;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxBrand = new javax.swing.JComboBox();
        jComboBoxModel = new javax.swing.JComboBox();
        jComboBoxFF = new javax.swing.JComboBox();
        jTextFieldUntil = new javax.swing.JTextField();
        jTextFieldSince = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCat = new javax.swing.JComboBox();
        jComboBoxPart = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBrandActionPerformed(evt);
            }
        });

        jLabel1.setText("year since:");

        jLabel2.setText("year until:");

        jComboBoxCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCatActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxFF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUntil)
                            .addComponent(jTextFieldSince, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addComponent(jComboBoxPart, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldUntil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jComboBoxFF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBrandActionPerformed
        this.jComboBoxModel.removeAllItems();
	try {
	    for(String cm : DBCarModel.getModelList(this.jComboBoxBrand.getSelectedItem().toString())){
		this.jComboBoxModel.addItem(cm);
	    }
	} catch (DBInteractionException ex) {
    	    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
	    Logger.getLogger(CarAdding.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
	}
    }//GEN-LAST:event_jComboBoxBrandActionPerformed

    private void jComboBoxCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCatActionPerformed
        this.jComboBoxPart.removeAllItems();
	if (!jComboBoxCat.getSelectedItem().toString().equals("")){
	    try {
		this.jComboBoxPart.addItem("");
		for(Part cm : Part.getListForCategory(Converter.getCategoryByString(jComboBoxCat.getSelectedItem().toString()))){
		    this.jComboBoxPart.addItem(cm);
		}
	    } catch (DBInteractionException ex) {
		JOptionPane.showMessageDialog(this, "Can't get part's list" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		Logger.getLogger(CarAdding.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
	    }
	}
    }//GEN-LAST:event_jComboBoxCatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	Part pt=null;
	int cat=0;
	if (!(this.jComboBoxPart.getSelectedItem()==null || this.jComboBoxPart.getSelectedItem().toString().equals(""))){
	   pt = (Part)this.jComboBoxPart.getSelectedItem();
	} else{
	    if(this.jComboBoxCat.getSelectedItem()!=null && !this.jComboBoxCat.getSelectedItem().toString().equals("")){
		cat=Converter.getCategoryByString(this.jComboBoxCat.getSelectedItem().toString());
	    }
	}
	try{
	    int yearS = new Integer(this.jTextFieldSince.getText());
	    int yearU = new Integer(this.jTextFieldUntil.getText());
	    int ff = (this.jComboBoxFF.getSelectedItem()=="" || this.jComboBoxFF.getSelectedItem()==null)? 0 : Converter.getFactorByString(this.jComboBoxFF.getSelectedItem().toString());
	    PartForSale pfs = new PartForSale((long)0, this.jComboBoxBrand.getSelectedItem().toString(), this.jComboBoxModel.getSelectedItem().toString(),
			   ff, yearS ,yearU , cat, pt, seller);
	    pfs.insert();
	    seller.addPartForSale(pfs);
	    JOptionPane.showMessageDialog(this, "Part for sale added ", "Info", JOptionPane.INFORMATION_MESSAGE);
	    this.dispose();
	} catch (DBInteractionException ex) {
	    Logger.getLogger(NewPartForSale.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
	    JOptionPane.showMessageDialog(this, "Can't insert Part:\n " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
	} catch(NumberFormatException nfex){
	    JOptionPane.showMessageDialog(this, "Wrong data", "Error", JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxBrand;
    private javax.swing.JComboBox jComboBoxCat;
    private javax.swing.JComboBox jComboBoxFF;
    private javax.swing.JComboBox jComboBoxModel;
    private javax.swing.JComboBox jComboBoxPart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldSince;
    private javax.swing.JTextField jTextFieldUntil;
    // End of variables declaration//GEN-END:variables
    
}

