/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.Car.Car;
import BusinessLogic.Customer;
import BusinessLogic.Part.Converter;
import BusinessLogic.Part.Part;
import BusinessLogic.Part.PartRequest;
import BusinessLogic.Tender;
import Exceptions.DBInteractionException;
import Exceptions.ServiceException;
import Service.ClientGetPartPrice.JSONPartPriceResponse;
import Service.ClientGetPartPrice.PartPriceHttpConnector;
import Service.ClientGetPartPrice.Request;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONException;

/**
 *
 * @author HOME
 */
public class TenderAdding extends javax.swing.JDialog {

    /**
     * Creates new form TenderAdding
     */
    public TenderAdding(java.awt.Frame parent, boolean modal, Car car, Customer cust) {
	super(parent, modal);
	this.car=car;
	this.cust=cust;
	initComponents();
    }

    Car car;
    Customer cust;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCat = new javax.swing.JComboBox(Converter.getCategoryList());
        jComboBoxParts = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCatActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose part's category:");

        jLabel2.setText("Choose part:");

        jLabel3.setText("Enter part number:");

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxParts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 316, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxParts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCatActionPerformed
	this.jComboBoxParts.removeAllItems();
	try {
	    for(Part cm : Part.getListForCategory(Converter.getCategoryByString(jComboBoxCat.getSelectedItem().toString()))){
		this.jComboBoxParts.addItem(cm);
	    }
	} catch (DBInteractionException ex) {
    	    JOptionPane.showMessageDialog(this, "Can't get part's list" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
	    Logger.getLogger(CarAdding.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
	}
    }//GEN-LAST:event_jComboBoxCatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	int pt_price =0;
	try{
	    pt_price = new JSONPartPriceResponse(PartPriceHttpConnector.executeRequest(new Request(this.jTextField1.getText()))).getPrice();
	} catch (JSONException | ServiceException ex){
	    if(JOptionPane.YES_OPTION!=JOptionPane.showOptionDialog(this, "Can't get shop price for this part\n Continue with zero price?", "Service warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null)){
		Logger.getLogger(TenderAdding.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
		JOptionPane.showMessageDialog(this, "Tender was't added: " + ex.getMessage(), "Info", JOptionPane.INFORMATION_MESSAGE);
		return;
	    }
	}
	try {
	    PartRequest pr = new PartRequest((long)0, this.car, (Part)this.jComboBoxParts.getSelectedItem(), this.jTextField1.getText(), pt_price);
	    Tender t = new Tender((long)0, pr, this.cust, new Date(0));
	    cust.addTender(t);
	    JOptionPane.showMessageDialog(this, "Tender added", "Info", JOptionPane.INFORMATION_MESSAGE);
	    this.dispose();
	} catch (DBInteractionException ex) {
       	    JOptionPane.showMessageDialog(this, "Can't add tender: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
	    Logger.getLogger(TenderAdding.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxCat;
    private javax.swing.JComboBox jComboBoxParts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
